FROM ubuntu:latest
RUN echo Updating existing packages, installing and upgrading python and pip.
RUN apt-get update -y
RUN apt-get install -y apache2
RUN service apache2 start
COPY ./index.html /var/www/html/
WORKDIR /MythicalMysfitsService